create extension if not exists pgcrypto;
create type public.app_role as enum ('admin','technician','user');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,email text,full_name text,role app_role not null default 'user',is_active boolean not null default true,created_at timestamptz default now());
create table public.equipment(id uuid primary key default gen_random_uuid(),name text not null,plant text,code_number text unique not null,funloc text,created_at timestamptz default now());
create table public.works(id uuid primary key default gen_random_uuid(),title text not null,description text,equipment_id uuid references public.equipment(id),work_type text not null check(work_type in ('Preventive Maintenance','Condition Monitoring','Corrective Maintenance','Others')),priority text not null check(priority in ('Low','Medium','High','Critical')),pic text not null,due_date date,status text not null default 'Open' check(status in ('Open','Proses','Selesai')),before_photo_path text,after_photo_path text,signature_path text,created_by uuid references auth.users(id),completed_at timestamptz,verified_at timestamptz,verified_by uuid references auth.users(id),verified_by_name text,created_at timestamptz default now(),updated_at timestamptz default now());
create or replace function public.my_role() returns app_role language sql stable security definer set search_path=public as $$select role from profiles where id=auth.uid() and is_active=true$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',new.email));return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
alter table profiles enable row level security;alter table equipment enable row level security;alter table works enable row level security;
create policy "read own/profile admin" on profiles for select to authenticated using(id=auth.uid() or my_role()='admin');create policy "admin updates profile" on profiles for update to authenticated using(my_role()='admin') with check(my_role()='admin');
create policy "authenticated read equipment" on equipment for select to authenticated using(true);create policy "admin manage equipment" on equipment for all to authenticated using(my_role()='admin') with check(my_role()='admin');
create policy "active users read works" on works for select to authenticated using(my_role() is not null);create policy "admin insert works" on works for insert to authenticated with check(my_role()='admin');create policy "admin delete works" on works for delete to authenticated using(my_role()='admin');
create policy "role update works" on works for update to authenticated using(my_role() in ('admin','technician','user')) with check(my_role() in ('admin','technician','user'));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('work-photos','work-photos',true,10485760,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=true;
create policy "authenticated view photos" on storage.objects for select to authenticated using(bucket_id='work-photos');create policy "authenticated upload photos" on storage.objects for insert to authenticated with check(bucket_id='work-photos');create policy "owner/admin change photos" on storage.objects for update to authenticated using(bucket_id='work-photos');
-- Setelah user pertama mendaftar, jadikan admin melalui SQL Editor:
-- update public.profiles set role='admin' where email='EMAIL_ADMIN_ANDA';