const C=window.APP_CONFIG;const sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let session=null,profile=null,works=[],equipment=[],signWorkId=null;const toast=(m,e=false)=>{let t=$('#toast');t.textContent=m;t.className='toast show'+(e?' error':'');setTimeout(()=>t.className='toast',3200)};const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function init(){ $('#today').textContent=new Intl.DateTimeFormat('id-ID',{dateStyle:'full'}).format(new Date()); const {data}=await sb.auth.getSession(); if(data.session) await enter(data.session); else showLogin(); sb.auth.onAuthStateChange(async(_,s)=>s?enter(s):showLogin()); bind(); }
function bind(){ $('#loginForm').onsubmit=login;$('#logoutBtn').onclick=()=>sb.auth.signOut();$$('#nav button').forEach(b=>b.onclick=()=>page(b.dataset.page,b));$$('[data-goto]').forEach(b=>b.onclick=()=>page(b.dataset.goto,$(`[data-page="${b.dataset.goto}"]`)));$('#addBtn').onclick=()=>openWork();$('#modalClose').onclick=$('#cancelBtn').onclick=()=>$('#modal').classList.add('hidden');$('#workForm').onsubmit=saveWork;$('#searchInput').oninput=renderWorks;['statusFilter','priorityFilter','typeFilter','picFilter'].forEach(id=>$(`#${id}`).oninput=renderWorks);$('#resetFilter').onclick=()=>{['searchInput','statusFilter','priorityFilter','typeFilter','picFilter'].forEach(id=>$(`#${id}`).value='');renderWorks()};$('#exportBtn').onclick = async () => {
try {
await exportXlsx(false);
} catch (error) {
console.error("Export XLSX gagal:", error);
toast("Export gagal: " + error.message, true);
}
};$('#emailBtn').onclick=sendEmail;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=importWorks;$('#masterImportBtn').onclick=()=>$('#masterFile').click();$('#masterFile').onchange=importMaster;$('#masterAddBtn').onclick=()=>editMaster();$('#userAddBtn').onclick=inviteUser;$('#clearSignature').onclick=clearSig;$('#saveSignature').onclick=saveVerification;$$('[data-close-sign]').forEach(x=>x.onclick=()=>$('#signatureModal').classList.add('hidden'));setupCanvas()}
async function login(e){e.preventDefault();$('#loginMsg').textContent='Memeriksa...';let {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});$('#loginMsg').textContent=error?error.message:''}
function showLogin(){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden')}
async function enter(s){session=s;let {data,error}=await sb.from('profiles').select('*').eq('id',s.user.id).single();if(error){toast('Profil pengguna belum tersedia',true);return}profile=data;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=profile.full_name||s.user.email;$('#userRole').textContent=profile.role;$$('[data-role="admin"]').forEach(el=>el.classList.toggle('hidden',profile.role!=='admin'));await Promise.all([loadEquipment(),loadWorks(),profile.role==='admin'?loadUsers():Promise.resolve()]);}
function page(n,b){$$('.page').forEach(x=>x.classList.add('hidden'));$(`#${n}Page`).classList.remove('hidden');$$('#nav button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');$('#pageTitle').textContent={dashboard:'Dashboard',works:'Pekerjaan',manage:'Kelola Master',users:'Kelola Pengguna'}[n]}
async function loadWorks(){let {data,error}=await sb.from('works').select('*,equipment(*)').order('created_at',{ascending:false});if(error)return toast(error.message,true);works=data||[];renderAll()}
async function loadEquipment(){let {data,error}=await sb.from('equipment').select('*').order('name');if(error)return toast(error.message,true);equipment=data||[];$('#equipmentId').innerHTML='<option value="">Pilih equipment</option>'+equipment.map(x=>`<option value="${x.id}">${esc(x.name)} | ${esc(x.code_number)}</option>`).join('');renderMaster()}
function renderAll(){let done=works.filter(x=>x.status==='Selesai'&&x.verified_at).length;$('#kpiTotal').textContent=works.length;$('#kpiOpen').textContent=works.filter(x=>x.status==='Open').length;$('#kpiProcess').textContent=works.filter(x=>x.status==='Proses'||(x.status==='Selesai'&&!x.verified_at)).length;$('#kpiDone').textContent=done;$('#recentList').innerHTML=works.slice(0,6).map(x=>`<div class="recent-item"><div><strong>${esc(x.title)}</strong><br><small>${esc(x.equipment?.name||'-')} • ${esc(x.pic)}</small></div><span class="badge ${x.status}">${x.verified_at?'Selesai':esc(x.status)}</span></div>`).join('')||'<p class="muted">Belum ada data.</p>';renderWorks()}
function filtered(){let q=$('#searchInput').value.toLowerCase(),s=$('#statusFilter').value,p=$('#priorityFilter').value,t=$('#typeFilter').value,pic=$('#picFilter').value.toLowerCase();return works.filter(x=>[x.title,x.pic,x.equipment?.name].join(' ').toLowerCase().includes(q)&&(!s||x.status===s)&&(!p||x.priority===p)&&(!t||x.work_type===t)&&(!pic||x.pic.toLowerCase().includes(pic)))}
function renderWorks(){let rows=filtered();$('#workTable').innerHTML=rows.map((x,i)=>`<tr><td>${i+1}</td><td><strong>${esc(x.title)}</strong><br><small>${esc(x.description||'')}</small></td><td>${esc(x.equipment?.name||'-')}</td><td>${esc(x.work_type)}</td><td>${esc(x.priority)}</td><td>${esc(x.pic)}</td><td><span class="badge ${x.status}">${x.verified_at?'Selesai':esc(x.status)}</span></td><td>${photo(x.before_photo_path)} ${photo(x.after_photo_path)}</td><td>${x.verified_at?'✓ '+esc(x.verified_by_name||'Terverifikasi'):verifyButton(x)}</td><td>${actionButtons(x)}</td></tr>`).join('')||'<tr><td colspan="10" class="muted">Data tidak ditemukan.</td></tr>';$$('[data-edit]').forEach(b=>b.onclick=()=>openWork(b.dataset.edit));$$('[data-del]').forEach(b=>b.onclick=()=>delWork(b.dataset.del));$$('[data-finish]').forEach(b=>b.onclick=()=>finishWork(b.dataset.finish));$$('[data-verify]').forEach(b=>b.onclick=()=>openSignature(b.dataset.verify))}
function photo(path){if(!path)return '';let {data}=sb.storage.from(C.PHOTO_BUCKET).getPublicUrl(path);return `<a href="${data.publicUrl}" target="_blank"><img class="photo" src="${data.publicUrl}" alt="Foto"></a>`}
function verifyButton(x){return ['user','admin'].includes(profile.role)?`<button class="mini-btn" data-verify="${x.id}" ${!x.after_photo_path?'disabled title="Foto selesai wajib ada"':''}>Paraf & Verif</button>`:'Menunggu user'}
function actionButtons(x){let a=[];if(profile.role==='admin')a.push(`<button class="mini-btn" data-edit="${x.id}">✎</button><button class="mini-btn" data-del="${x.id}">🗑</button>`);if(profile.role==='technician'&&x.status!=='Selesai')a.push(`<button class="mini-btn" data-finish="${x.id}">✓ Selesai</button>`);return a.join('')||'-'}
function openWork(id){let x=works.find(w=>w.id===id);$('#modalTitle').textContent=x?'Edit Pekerjaan':'Tambah Pekerjaan';$('#workId').value=x?.id||'';$('#title').value=x?.title||'';$('#equipmentId').value=x?.equipment_id||'';$('#pic').value=x?.pic||'';$('#type').value=x?.work_type||'Preventive Maintenance';$('#priority').value=x?.priority||'Medium';$('#dueDate').value=x?.due_date||'';$('#status').value=x?.status||'Open';$('#description').value=x?.description||'';$('#modal').classList.remove('hidden')}
async function upload(file,workId,kind){if(!file)return null;let ext=file.name.split('.').pop().toLowerCase(),path=`${workId}/${kind}-${Date.now()}.${ext}`;let {error}=await sb.storage.from(C.PHOTO_BUCKET).upload(path,file,{upsert:true});if(error)throw error;return path}
async function saveWork(e){e.preventDefault();try{let id=$('#workId').value||crypto.randomUUID(),old=works.find(x=>x.id===id),payload={id,title:$('#title').value,equipment_id:$('#equipmentId').value,pic:$('#pic').value,work_type:$('#type').value,priority:$('#priority').value,due_date:$('#dueDate').value||null,status:$('#status').value,description:$('#description').value,created_by:old?.created_by||session.user.id};let bp=await upload($('#beforePhoto').files[0],id,'before'),ap=await upload($('#afterPhoto').files[0],id,'after');if(bp)payload.before_photo_path=bp;if(ap)payload.after_photo_path=ap;let {error}=await sb.from('works').upsert(payload);if(error)throw error;toast('Pekerjaan tersimpan');$('#modal').classList.add('hidden');await loadWorks()}catch(e){toast(e.message,true)}}
async function delWork(id){if(!confirm('Hapus pekerjaan ini?'))return;let {error}=await sb.from('works').delete().eq('id',id);if(error)return toast(error.message,true);toast('Pekerjaan dihapus');loadWorks()}
async function finishWork(id){let x=works.find(w=>w.id===id);if(!x.after_photo_path){openWork(id);toast('Tambahkan foto sesudah terlebih dahulu',true);return}let {error}=await sb.from('works').update({status:'Selesai',completed_at:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,true);toast('Pekerjaan selesai, menunggu verifikasi');loadWorks()}
function openSignature(id){let x=works.find(w=>w.id===id);if(!x.after_photo_path)return toast('Foto sesudah wajib tersedia',true);signWorkId=id;$('#signatureModal').classList.remove('hidden');clearSig()}
let ctx,drawing=false;function setupCanvas(){let c=$('#signatureCanvas');ctx=c.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';let pos=e=>{let r=c.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*c.width/r.width,y:(p.clientY-r.top)*c.height/r.height}};c.onpointerdown=e=>{drawing=true;let p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};c.onpointermove=e=>{if(!drawing)return;let p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()};c.onpointerup=c.onpointerleave=()=>drawing=false}
function clearSig(){ctx?.clearRect(0,0,$('#signatureCanvas').width,$('#signatureCanvas').height)}
async function saveVerification(){let blob=await new Promise(r=>$('#signatureCanvas').toBlob(r,'image/png'));if(!blob||blob.size<500)return toast('Buat paraf terlebih dahulu',true);let path=`signatures/${signWorkId}-${Date.now()}.png`;let {error}=await sb.storage.from(C.PHOTO_BUCKET).upload(path,blob,{contentType:'image/png'});if(error)return toast(error.message,true);let u=await sb.from('works').update({status:'Selesai',signature_path:path,verified_at:new Date().toISOString(),verified_by:session.user.id,verified_by_name:profile.full_name}).eq('id',signWorkId);if(u.error)return toast(u.error.message,true);$('#signatureModal').classList.add('hidden');toast('Pekerjaan terverifikasi');loadWorks()}
async function importWorks(e){let data=await readExcel(e.target.files[0]);let rows=data.map(r=>({title:r['Judul'],pic:r['PIC'],work_type:r['Jenis'],priority:r['Prioritas']||'Medium',due_date:excelDate(r['Tanggal Rencana']),status:r['Status']||'Open',description:r['Deskripsi']||'',equipment_id:equipment.find(x=>x.code_number==r['Code Number'])?.id,created_by:session.user.id})).filter(x=>x.title&&x.equipment_id);let {error}=await sb.from('works').insert(rows);if(error)return toast(error.message,true);toast(`${rows.length} pekerjaan diimpor`);loadWorks()}
async function importMaster(e){let data=await readExcel(e.target.files[0]);let rows=data.map(r=>({name:r['Equipment'],plant:r['Plant'],code_number:String(r['Code Number']||''),funloc:r['Funloc']})).filter(x=>x.name&&x.code_number);let {error}=await sb.from('equipment').upsert(rows,{onConflict:'code_number'});if(error)return toast(error.message,true);toast(`${rows.length} equipment diperbarui`);loadEquipment()}
async function readExcel(f){let buf=await f.arrayBuffer(),wb=XLSX.read(buf),ws=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(ws,{defval:''})}function excelDate(v){if(!v)return null;if(typeof v==='number'){let d=XLSX.SSF.parse_date_code(v);return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}return String(v).slice(0,10)}
function renderMaster(){$('#masterTable').innerHTML=equipment.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.plant)}</td><td>${esc(x.code_number)}</td><td>${esc(x.funloc)}</td><td><button class="mini-btn" onclick='editMaster(${JSON.stringify(x)})'>✎</button></td></tr>`).join('')}
window.editMaster=async x=>{let name=prompt('Nama equipment',x?.name||'');if(!name)return;let plant=prompt('Plant',x?.plant||''),code_number=prompt('Code Number',x?.code_number||''),funloc=prompt('Funloc',x?.funloc||'');let {error}=await sb.from('equipment').upsert({id:x?.id,name,plant,code_number,funloc});if(error)return toast(error.message,true);loadEquipment()}
async function loadUsers(){let {data}=await sb.from('profiles').select('*').order('full_name');$('#userTable').innerHTML=(data||[]).map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.email)}</td><td><select data-role-change="${x.id}"><option ${x.role==='admin'?'selected':''}>admin</option><option ${x.role==='technician'?'selected':''}>technician</option><option ${x.role==='user'?'selected':''}>user</option></select></td><td>${x.is_active?'Aktif':'Nonaktif'}</td><td><button class="mini-btn" data-toggle-user="${x.id}" data-active="${x.is_active}">${x.is_active?'Nonaktifkan':'Aktifkan'}</button></td></tr>`).join('');$$('[data-role-change]').forEach(s=>s.onchange=()=>updateProfile(s.dataset.roleChange,{role:s.value}));$$('[data-toggle-user]').forEach(b=>b.onclick=()=>updateProfile(b.dataset.toggleUser,{is_active:b.dataset.active!=='true'}))}
async function updateProfile(id,p){let {error}=await sb.from('profiles').update(p).eq('id',id);if(error)return toast(error.message,true);toast('Pengguna diperbarui');loadUsers()}
async function inviteUser(){let email=prompt('Email pengguna baru');if(!email)return;let full_name=prompt('Nama lengkap')||email,role=prompt('Role: admin / technician / user','user');let {data,error}=await sb.functions.invoke('admin-user',{body:{email,full_name,role}});toast(error?.message||data?.message||'Undangan diproses',!!error)}
async function exportXlsx(returnBlob=false){toast('Membuat XLSX...');let wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Report',{properties:{defaultRowHeight:55}});ws.columns=[{header:'No',key:'no',width:6},{header:'Pekerjaan',key:'title',width:32},{header:'Equipment',key:'equipment',width:22},{header:'Jenis',key:'type',width:24},{header:'Prioritas',key:'priority',width:12},{header:'PIC',key:'pic',width:18},{header:'Status',key:'status',width:14},{header:'Foto Sebelum',key:'before',width:18},{header:'Foto Sesudah',key:'after',width:18},{header:'Verifikasi',key:'verified',width:22}];ws.getRow(1).height=26;ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF1D4ED8'}};for(let [i,x] of filtered().entries()){let row=ws.addRow({no:i+1,title:x.title,equipment:x.equipment?.name,type:x.work_type,priority:x.priority,pic:x.pic,status:x.verified_at?'Selesai':x.status,verified:x.verified_by_name||''});row.height=82;for(let [path,col] of [[x.before_photo_path,8],[x.after_photo_path,9]])if(path){try{let {data}=sb.storage.from(C.PHOTO_BUCKET).getPublicUrl(path),blob=await fetch(data.publicUrl).then(r=>r.blob()),compressed=await compress(blob),buf=await compressed.arrayBuffer(),ext=compressed.type.includes('png')?'png':'jpeg',img=wb.addImage({buffer:buf,extension:ext});ws.addImage(img,{tl:{col:col-1+.08,row:i+1+.08},ext:{width:110,height:75}})}catch{}}}ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:'A1',to:'J1'};let buf=await wb.xlsx.writeBuffer(),blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});if(returnBlob)return blob;saveAs(blob,`maintenance-report-${new Date().toISOString().slice(0,10)}.xlsx`);toast('XLSX berhasil dibuat')}
async function compress(blob){let bm=await createImageBitmap(blob),max=900,scale=Math.min(1,max/Math.max(bm.width,bm.height)),c=document.createElement('canvas');c.width=bm.width*scale;c.height=bm.height*scale;c.getContext('2d').drawImage(bm,0,0,c.width,c.height);return await new Promise(r=>c.toBlob(r,'image/jpeg',.72))}
async function sendEmail(){let recipient=prompt('Kirim report ke email:',C.REPORT_RECIPIENT);if(!recipient)return;let blob=await exportXlsx(true),b64=await blobToBase64(blob);let {data,error}=await sb.functions.invoke('send-report',{body:{to:recipient,filename:`maintenance-report-${new Date().toISOString().slice(0,10)}.xlsx`,attachmentBase64:b64}});toast(error?.message||data?.message||'Email terkirim',!!error)}function blobToBase64(b){return new Promise((r,j)=>{let f=new FileReader;f.onload=()=>r(f.result.split(',')[1]);f.onerror=j;f.readAsDataURL(b)})}
init();