"use strict";
(function(){
const $=s=>document.querySelector(s),norm=v=>String(v||"").trim().toLowerCase();
const bind=(id,event,fn)=>{const el=document.getElementById(id);if(el)el[event]=fn};
const reportName=()=>{const d=new Date();return `maintenance-report-${String(d.getDate()).padStart(2,"0")}-${String(d.getMonth()+1).padStart(2,"0")}-${d.getFullYear()}.xlsx`};
function readExcel(file){return new Promise((resolve,reject)=>{if(!file)return reject(Error("Pilih file Excel."));const r=new FileReader;r.onload=()=>{try{const b=XLSX.read(r.result,{type:"array",cellDates:true});resolve(XLSX.utils.sheet_to_json(b.Sheets[b.SheetNames[0]],{defval:"",raw:false}))}catch(e){reject(e)}};r.onerror=()=>reject(Error("File gagal dibaca."));r.readAsArrayBuffer(file)})}
function value(row,names){const a=names.map(norm),k=Object.keys(row).find(x=>a.includes(norm(x)));return k?row[k]:""}
function dateValue(v){if(!v)return null;const t=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(t))return t.slice(0,10);const m=t.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:null}
async function importWorks(e){try{const rows=await readExcel(e.target.files?.[0]),payload=[];for(const r of rows){const title=String(value(r,["Pekerjaan","Judul","Title"])).trim(),eqText=String(value(r,["Equipment","Nama Equipment","Code Number"])).trim(),eq=equipment.find(x=>norm(x.name)===norm(eqText)||norm(x.code_number)===norm(eqText));if(!title||!eq)continue;payload.push({title,equipment_id:eq.id,work_type:String(value(r,["Jenis","Work Type"])).trim()||"Others",priority:String(value(r,["Prioritas","Priority"])).trim()||"Medium",pic:String(value(r,["PIC"])).trim(),status:String(value(r,["Status"])).trim()||"Open",description:String(value(r,["Deskripsi","Description"])).trim(),due_date:dateValue(value(r,["Tanggal Rencana","Due Date","Tanggal"])),created_by:session.user.id})}if(!payload.length)throw Error("Tidak ada baris valid. Equipment harus cocok dengan Master Data.");const{error}=await sb.from("works").insert(payload);if(error)throw error;toast(`${payload.length} pekerjaan berhasil diunggah.`);await loadWorks()}catch(err){toast("Mass upload pekerjaan gagal: "+err.message,true)}finally{e.target.value=""}}
async function importEquipment(e){try{const rows=await readExcel(e.target.files?.[0]),payload=rows.map(r=>({name:String(value(r,["Equipment","Name","Nama Equipment"])).trim(),plant:String(value(r,["Plant"])).trim(),code_number:String(value(r,["Code Number","Code_Number","Kode"])).trim(),funloc:String(value(r,["Funloc","Functional Location"])).trim()})).filter(x=>x.name);if(!payload.length)throw Error("Tidak ada equipment valid.");const{error}=await sb.from("equipment").upsert(payload);if(error)throw error;toast(`${payload.length} equipment berhasil diunggah.`);await loadEquipment()}catch(err){toast("Mass upload equipment gagal: "+err.message,true)}finally{e.target.value=""}}
async function addEquipment(){if(norm(profile?.role)!=="admin")return toast("Hanya admin yang dapat menambah equipment.",true);const name=prompt("Nama Equipment");if(!name)return;const{error}=await sb.from("equipment").insert({name:name.trim(),plant:(prompt("Plant")||"").trim(),code_number:(prompt("Code Number")||"").trim(),funloc:(prompt("Functional Location")||"").trim()});if(error)return toast(error.message,true);toast("Equipment berhasil ditambahkan.");await loadEquipment()}
async function addPhoto(book,sheet,path,col,row){if(!path)return;try{let blob;try{const r=await fetch(photoUrl(path),{cache:"no-store"});if(r.ok)blob=await r.blob()}catch{}if(!blob){const d=await sb.storage.from(C.PHOTO_BUCKET).download(path);if(d.error)throw d.error;blob=d.data}const bitmap=await createImageBitmap(blob),canvas=document.createElement("canvas"),scale=Math.min(1,900/bitmap.width,700/bitmap.height);canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const c=canvas.getContext("2d");c.fillStyle="#fff";c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(bitmap,0,0,canvas.width,canvas.height);const jpg=await new Promise(r=>canvas.toBlob(r,"image/jpeg",.72)),id=book.addImage({buffer:await jpg.arrayBuffer(),extension:"jpeg"});sheet.addImage(id,{tl:{col:col-1+.1,row:row-1+.1},ext:{width:120,height:82}})}catch(err){console.error(err)}}
async function exportXlsx(ret=false){try{const rows=filtered();if(!rows.length)throw Error("Tidak ada data untuk diekspor.");toast("Membuat XLSX...");const book=new ExcelJS.Workbook(),sheet=book.addWorksheet("Report");sheet.columns=[{header:"No",key:"no",width:7},{header:"Pekerjaan",key:"title",width:32},{header:"Equipment",key:"eq",width:24},{header:"Jenis",key:"type",width:25},{header:"Prioritas",key:"priority",width:14},{header:"PIC",key:"pic",width:18},{header:"Bulan",key:"month",width:18},{header:"Status",key:"status",width:18},{header:"Foto Sebelum",key:"before",width:19},{header:"Foto Sesudah",key:"after",width:19}];for(let i=0;i<rows.length;i++){const x=rows[i],r=sheet.addRow({no:i+1,title:x.title,eq:x.equipment?.name||"-",type:x.work_type,priority:x.priority,pic:x.pic,month:monthLabel(x.due_date),status:x.verified_at?"Terverifikasi":x.status,before:x.before_photo_path?"":"Tidak ada",after:x.after_photo_path?"":"Tidak ada"});r.height=72;await addPhoto(book,sheet,x.before_photo_path,9,i+2);await addPhoto(book,sheet,x.after_photo_path,10,i+2)}const blob=new Blob([await book.xlsx.writeBuffer()],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});if(ret)return blob;saveAs(blob,reportName());toast("XLSX berhasil dibuat.");return blob}catch(err){toast("Export gagal: "+err.message,true);return null}}
async function sendEmail(){const to=prompt("Email penerima",C.REPORT_RECIPIENT||"");if(!to)return;try{const blob=await exportXlsx(true);if(!blob)throw Error("XLSX gagal dibuat.");const base64=await new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(String(r.result).split(",")[1]);r.onerror=reject;r.readAsDataURL(blob)});toast("Mengirim melalui Gmail...");const{data,error}=await sb.functions.invoke("send-report",{body:{to:to.trim(),filename:reportName(),attachmentBase64:base64}});if(error)throw error;if(!data?.success)throw Error(data?.error||"Email gagal dikirim.");toast(data.message||"Email berhasil dikirim.")}catch(err){toast("Kirim email gagal: "+err.message,true)}}
function wire(){bind("emailBtn","onclick",sendEmail);bind("exportBtn","onclick",()=>exportXlsx(false));bind("importWorksBtn","onclick",()=>$("#importWorksFile")?.click());bind("importWorksFile","onchange",importWorks);bind("importEquipmentBtn","onclick",()=>$("#importEquipmentFile")?.click());bind("importEquipmentFile","onchange",importEquipment);bind("masterAddBtn","onclick",addEquipment)}
window.addEventListener("load",wire);setTimeout(wire,500);
})();
