"use strict";
const C=window.APP_CONFIG,sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let session,profile,works=[],equipment=[];
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));const icons=()=>lucide?.createIcons();
function toast(m,e=false){const t=$("#toast");t.textContent=m;t.className="toast show"+(e?" error":"");clearTimeout(toast.t);toast.t=setTimeout(()=>t.className="toast",4000)}
function name(){const d=new Date();return `maintenance-report-${String(d.getDate()).padStart(2,"0")}-${String(d.getMonth()+1).padStart(2,"0")}-${d.getFullYear()}.xlsx`}
function photoUrl(p){return p?sb.storage.from(C.PHOTO_BUCKET).getPublicUrl(p).data.publicUrl:null}
function workMonth(dateValue){
  if(!dateValue)return "-";
  const parts=String(dateValue).slice(0,10).split("-");
  if(parts.length<2)return "-";
  const date=new Date(Number(parts[0]),Number(parts[1])-1,1);
  return new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(date);
}
async function init(){bind();icons();$("#today").textContent=new Intl.DateTimeFormat("id-ID",{dateStyle:"full"}).format(new Date());const{data}=await sb.auth.getSession();data.session?enter(data.session):loginView();sb.auth.onAuthStateChange((_,s)=>s?enter(s):loginView())}
function bind(){$("#loginForm").onsubmit=login;$("#logoutBtn").onclick=()=>sb.auth.signOut();$$("#nav button").forEach(b=>b.onclick=()=>page(b.dataset.page,b));$$('[data-goto]').forEach(b=>b.onclick=()=>page(b.dataset.goto,$(`[data-page="${b.dataset.goto}"]`)));$$('[data-close]').forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.add("hidden"));$("#addBtn").onclick=()=>openForm();$("#workForm").onsubmit=saveWork;$("#workTable").onclick=actions;$("#resetFilter").onclick=()=>{["searchInput","statusFilter","priorityFilter","typeFilter","picFilter","monthFilter"].forEach(x=>$("#"+x).value="");renderWorks()};["searchInput","statusFilter","priorityFilter","typeFilter","picFilter","monthFilter"].forEach(x=>$("#"+x).oninput=renderWorks);$("#importWorksBtn").onclick=()=>$("#importWorksFile").click();$("#importWorksFile").onchange=importWorks;$("#importEquipmentBtn").onclick=()=>$("#importEquipmentFile").click();$("#importEquipmentFile").onchange=importEquipment;$("#masterAddBtn").onclick=()=>editEquipment();$("#exportBtn").onclick=()=>exportXlsx(false);$("#emailBtn").onclick=sendEmail}
async function login(e){e.preventDefault();const{error}=await sb.auth.signInWithPassword({email:$("#loginEmail").value.trim(),password:$("#loginPassword").value});$("#loginMsg").textContent=error?error.message:""}
function loginView(){$("#loginView").classList.remove("hidden");$("#appView").classList.add("hidden")}
async function enter(s){session=s;const{data,error}=await sb.from("profiles").select("*").eq("id",s.user.id).single();if(error)return toast(error.message,true);profile=data;$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#userName").textContent=data.full_name||s.user.email;$("#userRole").textContent=data.role;$$('[data-admin]').forEach(x=>x.classList.toggle("hidden",data.role!=="admin"));await Promise.all([loadEquipment(),loadWorks(),data.role==="admin"?loadUsers():0]);icons()}
function page(n,b){$$(".page").forEach(x=>x.classList.add("hidden"));$("#"+n+"Page").classList.remove("hidden");$$("#nav button").forEach(x=>x.classList.remove("active"));b?.classList.add("active");$("#pageTitle").textContent={dashboard:"Dashboard",works:"Pekerjaan",manage:"Master Data",users:"Pengguna"}[n]}
async function loadWorks(){const{data,error}=await sb.from("works").select("*,equipment(*)").order("created_at",{ascending:false});if(error)return toast(error.message,true);works=data||[];render()}
async function loadEquipment(){const{data,error}=await sb.from("equipment").select("*").order("name");if(error)return toast(error.message,true);equipment=data||[];$("#equipmentId").innerHTML='<option value="">Pilih equipment</option>'+equipment.map(x=>`<option value="${x.id}">${esc(x.name)} | ${esc(x.code_number)}</option>`).join("");renderEquipment()}
function render(){$("#kpiTotal").textContent=works.length;$("#kpiOpen").textContent=works.filter(x=>x.status==="Open").length;$("#kpiProcess").textContent=works.filter(x=>x.status==="Proses").length;$("#kpiDone").textContent=works.filter(x=>x.verified_at).length;$("#recentList").innerHTML=works.slice(0,6).map(x=>`<div class="recent-item"><strong>${esc(x.title)}</strong><span class="badge ${x.status}">${x.verified_at?"Terverifikasi":x.status}</span></div>`).join("");renderWorks()}
function filtered(){
  const q=$("#searchInput").value.toLowerCase(),
    s=$("#statusFilter").value,
    p=$("#priorityFilter").value,
    t=$("#typeFilter").value,
    pic=$("#picFilter").value.toLowerCase(),
    month=$("#monthFilter").value;

  return works.filter(x=>{
    const searchable=[x.title,x.pic,x.equipment?.name].join(" ").toLowerCase();
    const workMonth=x.due_date?String(x.due_date).slice(0,7):"";

    return searchable.includes(q)&&
      (!s||x.status===s)&&
      (!p||x.priority===p)&&
      (!t||x.work_type===t)&&
      (!pic||String(x.pic||"").toLowerCase().includes(pic))&&
      (!month||workMonth===month);
  });
}
function renderWorks(){$("#workTable").innerHTML=filtered().map((x,i)=>`<tr><td>${i+1}</td><td><strong>${esc(x.title)}</strong><br><small>${esc(x.description||"")}</small></td><td>${esc(x.equipment?.name||"-")}</td><td>${esc(x.work_type)}</td><td>${esc(x.priority)}</td><td>${esc(x.pic)}</td><td><span class="month-cell"><i data-lucide="calendar-days"></i>${esc(workMonth(x.due_date))}</span></td><td><span class="badge ${x.status}">${x.verified_at?"Terverifikasi":x.status}</span></td><td>${[x.before_photo_path,x.after_photo_path].filter(Boolean).map(p=>`<img class="photo" src="${photoUrl(p)}">`).join(" ")}</td><td>${x.verified_by_name||"Belum"}</td><td><div class="action-group"><button data-detail="${x.id}" class="mini-btn"><i data-lucide="eye"></i>Detail</button>${profile.role==="admin"?`<button data-edit="${x.id}" class="mini-btn"><i data-lucide="pencil"></i>Edit</button><button data-del="${x.id}" class="mini-btn btn-danger"><i data-lucide="trash-2"></i>Hapus</button>`:""}</div></td></tr>`).join("");icons()}
function actions(e){const b=e.target.closest("button");if(!b)return;if(b.dataset.detail)detail(b.dataset.detail);if(b.dataset.edit)openForm(b.dataset.edit);if(b.dataset.del)del(b.dataset.del)}
function detail(id){const x=works.find(v=>v.id===id),item=(a,b,c="")=>`<div class="detail-item ${c}"><small>${a}</small><strong>${esc(b||"-")}</strong></div>`,img=p=>p?`<img class="detail-photo" src="${photoUrl(p)}">`:"Belum tersedia";$("#detailGrid").innerHTML=item("Judul",x.title,"span2")+item("Equipment",x.equipment?.name)+item("PIC",x.pic)+item("Jenis",x.work_type)+item("Prioritas",x.priority)+item("Status",x.status)+`<div class="detail-item span2"><small>Deskripsi</small><p>${esc(x.description||"-")}</p></div><div class="detail-item"><small>Foto sebelum</small>${img(x.before_photo_path)}</div><div class="detail-item"><small>Foto sesudah</small>${img(x.after_photo_path)}</div>`;$("#detailModal").classList.remove("hidden")}
function openForm(id){const x=works.find(v=>v.id===id);$("#workModalTitle").textContent=x?"Edit Pekerjaan":"Tambah Pekerjaan";[["workId",x?.id],["title",x?.title],["equipmentId",x?.equipment_id],["pic",x?.pic],["type",x?.work_type],["priority",x?.priority],["dueDate",x?.due_date],["status",x?.status],["description",x?.description]].forEach(([a,b])=>$("#"+a).value=b||"");$("#workModal").classList.remove("hidden")}
async function upload(f,id,k){if(!f)return null;const p=`${id}/${k}-${Date.now()}.${f.name.split('.').pop()}`,{error}=await sb.storage.from(C.PHOTO_BUCKET).upload(p,f);if(error)throw error;return p}
async function saveWork(e){e.preventDefault();try{const id=$("#workId").value||crypto.randomUUID(),old=works.find(x=>x.id===id),p={id,title:$("#title").value,equipment_id:$("#equipmentId").value,pic:$("#pic").value,work_type:$("#type").value,priority:$("#priority").value,due_date:$("#dueDate").value||null,status:$("#status").value,description:$("#description").value,created_by:old?.created_by||session.user.id},bf=await upload($("#beforePhoto").files[0],id,"before"),af=await upload($("#afterPhoto").files[0],id,"after");if(bf)p.before_photo_path=bf;if(af)p.after_photo_path=af;const{error}=await sb.from("works").upsert(p);if(error)throw error;$("#workModal").classList.add("hidden");loadWorks()}catch(x){toast(x.message,true)}}
async function del(id){if(confirm("Hapus pekerjaan?")){const{error}=await sb.from("works").delete().eq("id",id);error?toast(error.message,true):loadWorks()}}
function readExcel(f){return new Promise((r,j)=>{const x=new FileReader;x.onload=()=>{try{const w=XLSX.read(x.result,{type:"array"});r(XLSX.utils.sheet_to_json(w.Sheets[w.SheetNames[0]],{defval:""}))}catch(e){j(e)}};x.readAsArrayBuffer(f)})}
const val=(r,n)=>{const k=Object.keys(r).find(k=>n.includes(k.toLowerCase().trim()));return k?r[k]:""};
async function importWorks(e){try{const rows=await readExcel(e.target.files[0]),data=[];for(const r of rows){const q=String(val(r,["equipment","nama equipment"])).trim(),eq=equipment.find(x=>x.name.toLowerCase()===q.toLowerCase()||String(x.code_number).toLowerCase()===q.toLowerCase());if(eq)data.push({title:val(r,["pekerjaan","judul","title"]),equipment_id:eq.id,work_type:val(r,["jenis","work type"])||"Others",priority:val(r,["prioritas","priority"])||"Medium",pic:val(r,["pic"]),status:val(r,["status"])||"Open",description:val(r,["deskripsi","description"]),created_by:session.user.id})}const{error}=await sb.from("works").insert(data);if(error)throw error;toast(`${data.length} pekerjaan berhasil diupload`);loadWorks()}catch(x){toast(x.message,true)}e.target.value=""}
async function importEquipment(e){try{const rows=await readExcel(e.target.files[0]),data=rows.map(r=>({name:val(r,["equipment","name","nama equipment"]),plant:val(r,["plant"]),code_number:val(r,["code number","code_number","kode"]),funloc:val(r,["funloc","functional location"])})).filter(x=>x.name);const{error}=await sb.from("equipment").upsert(data);if(error)throw error;toast(`${data.length} equipment berhasil diupload`);loadEquipment()}catch(x){toast(x.message,true)}e.target.value=""}
function renderEquipment(){$("#masterTable").innerHTML=equipment.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.plant)}</td><td>${esc(x.code_number)}</td><td>${esc(x.funloc)}</td><td><button data-eq="${x.id}" class="mini-btn">Edit</button></td></tr>`).join("");$$('[data-eq]').forEach(b=>b.onclick=()=>editEquipment(equipment.find(x=>x.id===b.dataset.eq)))}
async function editEquipment(x){const name=prompt("Equipment",x?.name||"");if(!name)return;const{error}=await sb.from("equipment").upsert({id:x?.id,name,plant:prompt("Plant",x?.plant||""),code_number:prompt("Code Number",x?.code_number||""),funloc:prompt("Funloc",x?.funloc||"")});error?toast(error.message,true):loadEquipment()}
async function loadUsers(){const{data}=await sb.from("profiles").select("*");$("#userTable").innerHTML=(data||[]).map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.email)}</td><td>${x.role}</td><td>${x.is_active?"Aktif":"Nonaktif"}</td></tr>`).join("")}
async function exportXlsx(ret=false){const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet("Report");ws.columns=[{header:"No",key:"no",width:7},{header:"Pekerjaan",key:"title",width:30},{header:"Equipment",key:"eq",width:22},{header:"Jenis",key:"type",width:25},{header:"Prioritas",key:"prio",width:14},{header:"PIC",key:"pic",width:18},{header:"Bulan",key:"month",width:18},{header:"Status",key:"status",width:18}];filtered().forEach((x,i)=>ws.addRow({no:i+1,title:x.title,eq:x.equipment?.name,type:x.work_type,prio:x.priority,pic:x.pic,month:workMonth(x.due_date),status:x.status}));const blob=new Blob([await wb.xlsx.writeBuffer()],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});if(ret)return blob;saveAs(blob,name());return blob}
async function sendEmail(){const to=prompt("Email penerima",C.REPORT_RECIPIENT||"");if(!to)return;const blob=await exportXlsx(true),base64=await new Promise(r=>{const f=new FileReader;f.onload=()=>r(String(f.result).split(",")[1]);f.readAsDataURL(blob)}),{data,error}=await sb.functions.invoke("send-report",{body:{to,filename:name(),attachmentBase64:base64}});toast(error?error.message:data?.message||"Email terkirim",!!error)}
function setupSignatureCanvas(){const c=$("#signatureCanvas");if(!c)return}
async function inviteUser(){toast("Gunakan function admin-user untuk mengundang pengguna.")}
init();
