"use strict";
const C=window.APP_CONFIG,sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let session,profile,works=[],equipment=[],verifyId,ctx,drawing=false;
const icons=()=>window.lucide?.createIcons({attrs:{"stroke-width":1.9}});
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function toast(m,e=false){const t=$("#toast");t.textContent=m;t.className="toast show"+(e?" error":"");clearTimeout(toast.t);toast.t=setTimeout(()=>t.className="toast",4200)}
function url(p){return p?sb.storage.from(C.PHOTO_BUCKET).getPublicUrl(p).data.publicUrl:null}
function reportFileName(){const d=new Date();return `maintenance-report-${String(d.getDate()).padStart(2,"0")}-${String(d.getMonth()+1).padStart(2,"0")}-${d.getFullYear()}.xlsx`}
async function init(){bind();setupCanvas();icons();$("#today").textContent=new Intl.DateTimeFormat("id-ID",{dateStyle:"full"}).format(new Date());const{data}=await sb.auth.getSession();data.session?enter(data.session):showLogin();sb.auth.onAuthStateChange((_,s)=>s?enter(s):showLogin())}
function bind(){$("#loginForm").onsubmit=login;$("#logoutBtn").onclick=()=>sb.auth.signOut();$$("#nav button").forEach(b=>b.onclick=()=>page(b.dataset.page,b));$$('[data-goto]').forEach(b=>b.onclick=()=>page(b.dataset.goto,$(`[data-page="${b.dataset.goto}"]`)));$$('[data-close]').forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.add("hidden"));$("#addBtn").onclick=()=>openForm();$("#workForm").onsubmit=saveWork;$("#workTable").onclick=tableClick;["searchInput","statusFilter","priorityFilter","typeFilter","picFilter"].forEach(id=>$("#"+id).oninput=renderWorks);$("#resetFilter").onclick=reset;$("#photoForm").onsubmit=completeWork;$("#technicianPhoto").onchange=preview;$("#clearSignature").onclick=clearSign;$("#saveSignature").onclick=verify;$("#exportBtn").onclick=()=>exportXlsx();$("#emailBtn").onclick=sendEmail;$("#masterAddBtn").onclick=()=>editMaster();$("#userAddBtn").onclick=inviteUser;$("#importWorksBtn").onclick=()=>$("#importWorksFile").click();$("#importWorksFile").onchange=importWorks;$("#importEquipmentBtn").onclick=()=>$("#importEquipmentFile").click();$("#importEquipmentFile").onchange=importEquipment}
async function login(e){e.preventDefault();const b=$("#loginButton"),m=$("#loginMsg");b.disabled=true;m.textContent="Memeriksa akun...";const{error}=await sb.auth.signInWithPassword({email:$("#loginEmail").value.trim(),password:$("#loginPassword").value});m.textContent=error?error.message:"";b.disabled=false}
function showLogin(){$("#loginView").classList.remove("hidden");$("#appView").classList.add("hidden")}
async function enter(s){session=s;const{data,error}=await sb.from("profiles").select("*").eq("id",s.user.id).single();if(error||!data)return $("#loginMsg").textContent="Profil pengguna tidak tersedia: "+(error?.message||"");profile=data;$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");$("#userName").textContent=data.full_name||s.user.email;$("#userRole").textContent=data.role;$$('[data-admin]').forEach(x=>x.classList.toggle("hidden",data.role!=="admin"));await Promise.all([loadEquipment(),loadWorks(),data.role==="admin"?loadUsers():0]);icons()}
function page(n,b){if(["manage","users"].includes(n)&&profile.role!=="admin")return;$$(".page").forEach(x=>x.classList.add("hidden"));$("#"+n+"Page").classList.remove("hidden");$$("#nav button").forEach(x=>x.classList.remove("active"));b?.classList.add("active");$("#pageTitle").textContent={dashboard:"Dashboard",works:"Pekerjaan",manage:"Master Data",users:"Pengguna"}[n]}
async function loadWorks(){const{data,error}=await sb.from("works").select("*,equipment(*)").order("created_at",{ascending:false});if(error)return toast(error.message,true);works=data||[];render()}
async function loadEquipment(){const{data,error}=await sb.from("equipment").select("*").order("name");if(error)return toast(error.message,true);equipment=data||[];$("#equipmentId").innerHTML='<option value="">Pilih equipment</option>'+equipment.map(x=>`<option value="${x.id}">${esc(x.name)} | ${esc(x.code_number)}</option>`).join("");renderMaster()}
function render(){$("#kpiTotal").textContent=works.length;$("#kpiOpen").textContent=works.filter(x=>x.status==="Open").length;$("#kpiProcess").textContent=works.filter(x=>x.status==="Proses"||(x.status==="Selesai"&&!x.verified_at)).length;$("#kpiDone").textContent=works.filter(x=>x.verified_at).length;$("#recentList").innerHTML=works.slice(0,6).map(x=>`<div class="recent-item"><div><strong>${esc(x.title)}</strong><br><small class="muted">${esc(x.equipment?.name||"-")} • ${esc(x.pic)}</small></div><span class="badge ${x.status}">${x.verified_at?"Terverifikasi":x.status}</span></div>`).join("")||'<p class="muted">Belum ada data.</p>';renderWorks()}
function filtered(){const q=$("#searchInput").value.toLowerCase(),s=$("#statusFilter").value,p=$("#priorityFilter").value,t=$("#typeFilter").value,pic=$("#picFilter").value.toLowerCase();return works.filter(x=>[x.title,x.description,x.pic,x.equipment?.name].join(" ").toLowerCase().includes(q)&&(!s||x.status===s)&&(!p||x.priority===p)&&(!t||x.work_type===t)&&(!pic||String(x.pic||"").toLowerCase().includes(pic)))}
function reset(){["searchInput","statusFilter","priorityFilter","typeFilter","picFilter"].forEach(id=>$("#"+id).value="");renderWorks()}
function photo(p){const u=url(p);return u?`<a href="${u}" target="_blank"><img class="photo" src="${u}" alt="Foto"></a>`:""}
function verifyCell(x){if(x.verified_at)return "✓ "+esc(x.verified_by_name||"Terverifikasi");if(["user","admin"].includes(profile.role)&&x.status==="Selesai"&&x.after_photo_path)return `<button class="mini-btn btn-upload" data-verify="${x.id}"><i data-lucide="signature"></i>Verifikasi</button>`;return x.status==="Proses"?"Menunggu teknisi":x.status==="Selesai"?"Menunggu user":"Belum dimulai"}
function actions(x){const a=[`<button class="mini-btn" data-detail="${x.id}"><i data-lucide="eye"></i>Detail</button>`];if(profile.role==="admin")a.push(`<button class="mini-btn" data-edit="${x.id}"><i data-lucide="pencil"></i>Edit</button><button class="mini-btn btn-danger" data-delete="${x.id}"><i data-lucide="trash-2"></i>Hapus</button>`);if(profile.role==="technician"&&x.status==="Open")a.push(`<button class="mini-btn btn-start" data-start="${x.id}"><i data-lucide="play"></i>Mulai</button>`);if(profile.role==="technician"&&x.status==="Proses")a.push(`<button class="mini-btn btn-upload" data-photo="${x.id}"><i data-lucide="camera"></i>Foto</button>`);return `<div class="action-group">${a.join("")}</div>`}
function renderWorks(){$("#workTable").innerHTML=filtered().map((x,i)=>`<tr><td>${i+1}</td><td><strong>${esc(x.title)}</strong><br><small class="muted">${esc(x.description||"")}</small></td><td>${esc(x.equipment?.name||"-")}</td><td>${esc(x.work_type||"-")}</td><td>${esc(x.priority||"-")}</td><td>${esc(x.pic||"-")}</td><td><span class="badge ${x.status}">${x.verified_at?"Terverifikasi":x.status}</span></td><td>${photo(x.before_photo_path)} ${photo(x.after_photo_path)}</td><td>${verifyCell(x)}</td><td>${actions(x)}</td></tr>`).join("")||'<tr><td colspan="10">Data tidak ditemukan</td></tr>';icons()}
function tableClick(e){const b=e.target.closest("button");if(!b)return;if(b.dataset.detail)detail(b.dataset.detail);else if(b.dataset.edit)openForm(b.dataset.edit);else if(b.dataset.delete)del(b.dataset.delete);else if(b.dataset.start)start(b.dataset.start);else if(b.dataset.photo)openPhoto(b.dataset.photo);else if(b.dataset.verify)openVerify(b.dataset.verify)}
function detail(id){const x=works.find(w=>w.id===id);if(!x)return;const item=(a,b,c="")=>`<div class="detail-item ${c}"><small>${a}</small><strong>${esc(b||"-")}</strong></div>`,img=p=>url(p)?`<img class="detail-photo" src="${url(p)}" alt="Foto pekerjaan">`:'<span class="muted">Belum tersedia</span>';$("#detailGrid").innerHTML=item("Judul",x.title,"span2")+item("Equipment",x.equipment?.name)+item("PIC",x.pic)+item("Jenis",x.work_type)+item("Prioritas",x.priority)+item("Status",x.verified_at?"Terverifikasi":x.status)+`<div class="detail-item span2"><small>Deskripsi</small><p>${esc(x.description||"-")}</p></div><div class="detail-item"><small>Foto sebelum</small>${img(x.before_photo_path)}</div><div class="detail-item"><small>Foto sesudah</small>${img(x.after_photo_path)}</div>`;$("#detailModal").classList.remove("hidden")}
function openForm(id){if(profile.role!=="admin")return;const x=works.find(w=>w.id===id);$("#workModalTitle").textContent=x?"Edit Pekerjaan":"Tambah Pekerjaan";[["workId",x?.id],["title",x?.title],["equipmentId",x?.equipment_id],["pic",x?.pic],["type",x?.work_type||"Preventive Maintenance"],["priority",x?.priority||"Medium"],["dueDate",x?.due_date],["status",x?.status||"Open"],["description",x?.description]].forEach(([id,v])=>$("#"+id).value=v||"");$("#beforePhoto").value=$("#afterPhoto").value="";$("#workModal").classList.remove("hidden")}
async function upload(f,id,k){if(!f)return null;const p=`${id}/${k}-${Date.now()}.${f.name.split('.').pop()}`;const{error}=await sb.storage.from(C.PHOTO_BUCKET).upload(p,f,{contentType:f.type});if(error)throw error;return p}
async function saveWork(e){e.preventDefault();try{const id=$("#workId").value||crypto.randomUUID(),old=works.find(x=>x.id===id),p={id,title:$("#title").value.trim(),equipment_id:$("#equipmentId").value,pic:$("#pic").value.trim(),work_type:$("#type").value,priority:$("#priority").value,due_date:$("#dueDate").value||null,status:$("#status").value,description:$("#description").value.trim(),created_by:old?.created_by||session.user.id,updated_at:new Date().toISOString()},bf=await upload($("#beforePhoto").files[0],id,"before"),af=await upload($("#afterPhoto").files[0],id,"after");if(bf)p.before_photo_path=bf;if(af)p.after_photo_path=af;const{error}=await sb.from("works").upsert(p);if(error)throw error;$("#workModal").classList.add("hidden");toast("Pekerjaan disimpan");loadWorks()}catch(e){toast(e.message,true)}}
async function del(id){if(!confirm("Hapus pekerjaan?"))return;const{error}=await sb.from("works").delete().eq("id",id);error?toast(error.message,true):loadWorks()}
async function start(id){const{error}=await sb.rpc("technician_start_work",{p_work_id:id});error?toast(error.message,true):(toast("Pekerjaan dimulai"),loadWorks())}
function openPhoto(id){const x=works.find(w=>w.id===id);$("#photoWorkId").value=id;$("#photoWorkInfo").innerHTML=`<small class="eyebrow">PEKERJAAN</small><h3>${esc(x.title)}</h3><p class="muted">${esc(x.equipment?.name||"-")}</p>`;$("#technicianPhoto").value="";$("#photoPreview").classList.add("hidden");$("#photoModal").classList.remove("hidden")}
function preview(e){const f=e.target.files[0];if(!f)return;$("#previewImage").src=URL.createObjectURL(f);$("#photoPreview").classList.remove("hidden")}
async function completeWork(e){e.preventDefault();try{const id=$("#photoWorkId").value,f=$("#technicianPhoto").files[0];if(!f)throw Error("Foto wajib dipilih");const p=await upload(f,id,"after"),{error}=await sb.rpc("technician_complete_work",{p_work_id:id,p_after_photo_path:p});if(error)throw error;$("#photoModal").classList.add("hidden");toast("Foto berhasil. Menunggu verifikasi");loadWorks()}catch(e){toast(e.message,true)}}
function setupCanvas(){const c=$("#signatureCanvas");ctx=c.getContext("2d");ctx.lineWidth=3;ctx.lineCap="round";const pos=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.onpointerdown=e=>{drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};c.onpointermove=e=>{if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()};c.onpointerup=c.onpointerleave=()=>drawing=false}
function clearSign(){ctx.clearRect(0,0,$("#signatureCanvas").width,$("#signatureCanvas").height)}function openVerify(id){verifyId=id;clearSign();$("#signatureModal").classList.remove("hidden")}
async function verify(){try{const blob=await new Promise(r=>$("#signatureCanvas").toBlob(r));if(!blob||blob.size<500)throw Error("Buat paraf terlebih dahulu");const p=`signatures/${verifyId}-${Date.now()}.png`,up=await sb.storage.from(C.PHOTO_BUCKET).upload(p,blob);if(up.error)throw up.error;const r=await sb.rpc("user_verify_work",{p_work_id:verifyId,p_signature_path:p});if(r.error)throw r.error;$("#signatureModal").classList.add("hidden");toast("Pekerjaan terverifikasi");loadWorks()}catch(e){toast(e.message,true)}}
function renderMaster(){$("#masterTable").innerHTML=equipment.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.plant||"-")}</td><td>${esc(x.code_number||"-")}</td><td>${esc(x.funloc||"-")}</td><td><button class="mini-btn" data-master="${x.id}">Edit</button></td></tr>`).join("");$$('[data-master]').forEach(b=>b.onclick=()=>editMaster(equipment.find(x=>x.id===b.dataset.master)))}
async function editMaster(x){if(profile?.role!=="admin")return;const name=prompt("Equipment",x?.name||"");if(!name)return;const p={id:x?.id,name,plant:prompt("Plant",x?.plant||"")||"",code_number:prompt("Code Number",x?.code_number||"")||"",funloc:prompt("Funloc",x?.funloc||"")||""},{error}=await sb.from("equipment").upsert(p);error?toast(error.message,true):loadEquipment()}
async function loadUsers(){const{data,error}=await sb.from("profiles").select("*");if(error)return toast(error.message,true);$("#userTable").innerHTML=(data||[]).map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.email)}</td><td>${esc(x.role)}</td><td>${x.is_active?"Aktif":"Nonaktif"}</td></tr>`).join("")}
async function inviteUser(){const email=prompt("Email pengguna");if(!email)return;const{error}=await sb.functions.invoke("admin-user",{body:{email,full_name:prompt("Nama lengkap")||email,role:prompt("Role: admin / technician / user","user")||"user"}});toast(error?error.message:"Undangan dikirim",!!error)}
function readExcel(file){return new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>{try{const wb=XLSX.read(r.result,{type:"array"});resolve(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""}))}catch(e){reject(e)}};r.onerror=()=>reject(Error("File gagal dibaca"));r.readAsArrayBuffer(file)})}
const val=(r,names)=>{const key=Object.keys(r).find(k=>names.some(n=>k.toLowerCase().trim()===n));return key?r[key]:""};
async function importWorks(e){const file=e.target.files[0];if(!file)return;try{const rows=await readExcel(file),payload=[];for(const r of rows){const equipmentName=String(val(r,["equipment","nama equipment"])).trim(),eq=equipment.find(x=>String(x.name).toLowerCase()===equipmentName.toLowerCase()||String(x.code_number).toLowerCase()===equipmentName.toLowerCase());if(!eq)continue;payload.push({title:String(val(r,["pekerjaan","judul","title"])).trim(),equipment_id:eq.id,work_type:String(val(r,["jenis","work type"])).trim()||"Others",priority:String(val(r,["prioritas","priority"])).trim()||"Medium",pic:String(val(r,["pic"])).trim(),status:String(val(r,["status"])).trim()||"Open",description:String(val(r,["deskripsi","description"])).trim(),created_by:session.user.id})}if(!payload.length)throw Error("Tidak ada baris valid. Pastikan nama equipment cocok.");const{error}=await sb.from("works").insert(payload);if(error)throw error;toast(`${payload.length} pekerjaan berhasil diupload`);loadWorks()}catch(err){toast(err.message,true)}finally{e.target.value=""}}
async function importEquipment(e){const file=e.target.files[0];if(!file)return;try{const rows=await readExcel(file),payload=rows.map(r=>({name:String(val(r,["equipment","name","nama equipment"])).trim(),plant:String(val(r,["plant"])).trim(),code_number:String(val(r,["code number","code_number","kode"])).trim(),funloc:String(val(r,["funloc","functional location"])).trim()})).filter(x=>x.name);if(!payload.length)throw Error("Tidak ada equipment valid");const{error}=await sb.from("equipment").upsert(payload);if(error)throw error;toast(`${payload.length} equipment berhasil diupload`);loadEquipment()}catch(err){toast(err.message,true)}finally{e.target.value=""}}
async function getPhotoBlob(p){try{const u=url(p);if(u){const r=await fetch(u,{cache:"no-store"});if(r.ok)return r.blob()}}catch{}const{data,error}=await sb.storage.from(C.PHOTO_BUCKET).download(p);if(error)throw error;return data}
async function addPhoto(wb,ws,p,col,row){if(!p)return;try{const blob=await getPhotoBlob(p),img=await createImageBitmap(blob),scale=Math.min(1,900/img.width,700/img.height),canvas=document.createElement("canvas");canvas.width=Math.max(1,img.width*scale);canvas.height=Math.max(1,img.height*scale);const c=canvas.getContext("2d");c.fillStyle="#fff";c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(img,0,0,canvas.width,canvas.height);const b=await new Promise(r=>canvas.toBlob(r,"image/jpeg",.72)),id=wb.addImage({buffer:await b.arrayBuffer(),extension:"jpeg"});ws.addImage(id,{tl:{col:col-1+.12,row:row-1+.1},ext:{width:120,height:82}})}catch(e){console.error("Foto Excel gagal",p,e)}}
async function exportXlsx(ret=false){try{const data=filtered();if(!data.length)throw Error("Tidak ada data");toast("Membuat XLSX...");const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet("Report");ws.columns=[{header:"No",key:"no",width:7},{header:"Pekerjaan",key:"title",width:32},{header:"Equipment",key:"eq",width:24},{header:"Jenis",key:"type",width:26},{header:"Prioritas",key:"prio",width:14},{header:"PIC",key:"pic",width:19},{header:"Status",key:"status",width:20},{header:"Foto Sebelum",key:"before",width:19},{header:"Foto Sesudah",key:"after",width:19},{header:"Verifikasi",key:"verify",width:24}];const h=ws.getRow(1);h.font={bold:true,color:{argb:"FFFFFFFF"}};h.fill={type:"pattern",pattern:"solid",fgColor:{argb:"FF2563EB"}};for(let i=0;i<data.length;i++){const x=data[i],r=ws.addRow({no:i+1,title:x.title,eq:x.equipment?.name,type:x.work_type,prio:x.priority,pic:x.pic,status:x.verified_at?"Terverifikasi":x.status,before:x.before_photo_path?"":"Tidak ada",after:x.after_photo_path?"":"Tidak ada",verify:x.verified_by_name||"Belum diverifikasi"});r.height=72;await addPhoto(wb,ws,x.before_photo_path,8,i+2);await addPhoto(wb,ws,x.after_photo_path,9,i+2)}ws.views=[{state:"frozen",ySplit:1}];const buf=await wb.xlsx.writeBuffer(),blob=new Blob([buf],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});if(ret)return blob;saveAs(blob,reportFileName());toast("XLSX berhasil dibuat");return blob}catch(e){toast(e.message,true);return null}}
async function sendEmail(){const to=prompt("Email penerima",C.REPORT_RECIPIENT||"");if(!to)return;try{const blob=await exportXlsx(true);if(!blob)throw Error("XLSX gagal dibuat");const base64=await new Promise((r,j)=>{const f=new FileReader;f.onload=()=>r(String(f.result).split(",")[1]);f.onerror=j;f.readAsDataURL(blob)}),{data,error}=await sb.functions.invoke("send-report",{body:{to:to.trim(),filename:reportFileName(),attachmentBase64:base64}});if(error)throw error;if(!data?.success)throw Error(data?.error||"Email gagal");toast(data.message||"Email berhasil dikirim")}catch(e){toast("Email gagal: "+e.message,true)}}
init().catch(e=>toast("Aplikasi gagal: "+e.message,true));
